package io.estebangarcia21.paper.web.sbt

import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}
import scala.collection.JavaConverters._

import Support._

private[sbt] object IconTooling {
  private val LucideVersion = "1.37.0"
  private val NamePattern = "[a-z0-9]+(?:-[a-z0-9]+)*".r

  private final case class Entry(name: String, version: String, sha256: String)

  def add(
      config: PaperwebConfig,
      name: String,
      downloader: Downloader
  ): Either[String, Seq[String]] =
    for {
      target <- requireTarget(config)
      _ <- validateName(name)
      downloaded <- download(name, LucideVersion, downloader)
      normalized = normalize(downloaded)
      bytes = normalized.getBytes(StandardCharsets.UTF_8)
      entry = Entry(name, LucideVersion, hash(bytes))
      entries <- readLock(config)
      updated = entries.filterNot(_.name == name) :+ entry
      _ <- write(cache(config).resolve(s"$name.svg"), bytes)
      _ <- writeLock(config, updated)
      _ <- generate(config, target, updated)
    } yield Seq(s"Added Icons.${methodName(name)} from Lucide $LucideVersion.")

  def remove(config: PaperwebConfig, name: String): Either[String, Seq[String]] =
    for {
      target <- requireTarget(config)
      entries <- readLock(config)
      _ <- either(entries.exists(_.name == name), s"$name is not configured.")
      updated = entries.filterNot(_.name == name)
      _ <- attempt(Files.deleteIfExists(cache(config).resolve(s"$name.svg"))).map(_ => ())
      _ <- writeLock(config, updated)
      _ <- generate(config, target, updated)
    } yield Seq(s"Removed $name.")

  def sync(
      config: PaperwebConfig,
      downloader: Downloader
  ): Either[String, Seq[String]] =
    for {
      target <- requireTarget(config)
      entries <- readLock(config)
      _ <- entries.foldLeft[Either[String, Unit]](Right(())) { (result, entry) =>
        result.flatMap(_ => restore(config, entry, downloader))
      }
      _ <- generate(config, target, entries)
    } yield Seq(s"Restored ${entries.size} Paperweb icons.")

  def list(config: PaperwebConfig): Either[String, Seq[String]] =
    readLock(config).map { entries =>
      if (entries.isEmpty) Seq("No icons are configured.")
      else entries.sortBy(_.name).map(entry => s"${entry.name} ${entry.version}")
    }

  private def restore(
      config: PaperwebConfig,
      entry: Entry,
      downloader: Downloader
  ): Either[String, Unit] = {
    val cached = cache(config).resolve(s"${entry.name}.svg")
    val validCache =
      if (Files.isRegularFile(cached))
        attempt(Files.readAllBytes(cached)).map(bytes => hash(bytes) == entry.sha256)
      else Right(false)

    validCache.flatMap {
      case true  => Right(())
      case false =>
        download(entry.name, entry.version, downloader).flatMap { svg =>
          val bytes = normalize(svg).getBytes(StandardCharsets.UTF_8)

          if (hash(bytes) != entry.sha256)
            Left(s"Checksum mismatch while restoring icon ${entry.name}.")
          else write(cached, bytes)
        }
    }
  }

  private def generate(
      config: PaperwebConfig,
      target: Path,
      entries: Seq[Entry]
  ): Either[String, Unit] = {
    for {
      scalaPackage <- config.scalaPackage.toRight(
        "paperweb.scala-package is required for icon generation."
      )
      methods <- entries
        .sortBy(_.name)
        .foldLeft[Either[String, Vector[String]]](Right(Vector.empty)) { (result, entry) =>
          for {
            existing <- result
            bytes <- attempt(Files.readAllBytes(cache(config).resolve(s"${entry.name}.svg")))
            _ <- either(hash(bytes) == entry.sha256, s"Cached icon ${entry.name} has changed.")
            svg = new String(bytes, StandardCharsets.UTF_8)
          } yield existing :+
            s"  def `${methodName(entry.name)}`: Frag = raw(${scalaString(svg)})"
        }
      body = if (methods.isEmpty) "" else methods.mkString("\n\n") + "\n"
      source =
        s"""package $scalaPackage
           |
           |import scalatags.Text.Frag
           |import scalatags.Text.all.raw
           |
           |/** Application-owned Lucide icons generated by Paperweb. */
           |object Icons:
           |$body""".stripMargin
      _ <- write(target, source.getBytes(StandardCharsets.UTF_8))
    } yield ()
  }

  private def download(
      name: String,
      version: String,
      downloader: Downloader
  ): Either[String, String] = {
    val url = s"https://cdn.jsdelivr.net/npm/lucide-static@$version/icons/$name.svg"
    downloader.get(url).map(bytes => new String(bytes, StandardCharsets.UTF_8))
  }

  private def normalize(svg: String): String =
    svg
      .replaceAll("(?s)<!--.*?-->", "")
      .replaceAll("\\s+", " ")
      .replaceFirst("class=\"lucide lucide-[^\"]*\"", "class=\"icon\"")
      .replace(" width=\"24\"", "")
      .replace(" height=\"24\"", "")
      .replaceAll("\\s+>", ">")
      .replaceAll("\\s+/>", "/>")
      .replaceAll("</svg>.*$", "</svg>")
      .replaceFirst("<svg ", "<svg aria-hidden=\"true\" focusable=\"false\" ")
      .trim

  private def validateName(name: String): Either[String, Unit] =
    either(
      NamePattern.pattern.matcher(name).matches(),
      "Icon names must use lowercase kebab-case."
    )

  private def methodName(name: String): String = {
    val parts = name.split("-")
    parts.head + parts.tail.map(part => part.head.toUpper + part.tail).mkString
  }

  private def scalaString(value: String): String =
    "\"" +
      value.flatMap {
        case '\\' => "\\\\"
        case '"'  => "\\\""
        case '\n' => "\\n"
        case '\r' => "\\r"
        case '\t' => "\\t"
        case char => char.toString
      } +
      "\""

  private def requireTarget(config: PaperwebConfig): Either[String, Path] =
    config.iconsOutput
      .map(_.toPath)
      .toRight(
        "Configure paperweb.scala-package or paperweb.icons-output before managing icons."
      )

  private def readLock(config: PaperwebConfig): Either[String, Vector[Entry]] = {
    val path = lock(config)

    if (!Files.isRegularFile(path)) Right(Vector.empty)
    else
      attempt(Files.readAllLines(path, StandardCharsets.UTF_8).asScala.toVector).flatMap { lines =>
        lines
          .filter(line => line.nonEmpty && !line.startsWith("#"))
          .foldLeft[Either[String, Vector[Entry]]](Right(Vector.empty)) { (result, line) =>
            line.split("\t", -1).toList match {
              case List(name, version, sha256) =>
                result.map(_ :+ Entry(name, version, sha256))
              case _ =>
                Left(s"Invalid icon entry in $path: $line")
            }
          }
      }
  }

  private def writeLock(
      config: PaperwebConfig,
      entries: Seq[Entry]
  ): Either[String, Unit] = {
    val rows = entries.sortBy(_.name).map { entry =>
      s"${entry.name}\t${entry.version}\t${entry.sha256}"
    }
    val contents =
      "# name\tlucide-version\tsha256\n" +
        rows.mkString("\n") +
        (if (rows.isEmpty) "" else "\n")

    write(lock(config), contents.getBytes(StandardCharsets.UTF_8))
  }

  private def lock(config: PaperwebConfig): Path =
    config.projectRoot.toPath.resolve(".paperweb/icons.lock")

  private def cache(config: PaperwebConfig): Path =
    config.projectRoot.toPath.resolve(".paperweb/icons")

}
